# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26b51552c44ee1f2d74b33dab1cebdab8424af23d479a12b4936bfc501a7e220270cea639745089caab9c46c4ded8b44cf3cd3bad4171a4f38c9f3c8aefad2c0

test:
  secret_key_base: e9730b8606081db55735a112c128fbf4bae2a0a51e967f4aea848bc2efd6317b48f53b64819ada598ded8126ce2b0b58968d1a7feb7f81a59adb0ff8278a87a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
